name: wanderhuman_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_login: ^5.1.0
  geolocator: ^14.0.2
  # lottie: ^3.3.1
  mapbox_maps_flutter: ^2.10.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/icons/
    - assets/icons/location_marker.png
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          style: normal
          weight: 700
    - family: Iansui
      fonts:
        - asset: assets\fonts\Iansui\Iansui-Regular.ttf
          style: normal
          weight: 400
